### ISSUE TITLE
NPKit for NCCL 2.18

### ISSUE THREAD

**Issue by tks2004** [microsoft/NPKit#24]
Hi, Can NPkit be used with NCCL 2.18v

**Comment by yzygitzh** [comment]
Hi,

You can try applying https://github.com/microsoft/NPKit/blob/main/nccl_samples/npkit-for-nccl-2.17.1-1.diff directly to NCCL 2.18. There should be limited revision efforts, according to our previous internal experience.

You can also reference AMD RCCL (https://github.com/ROCmSoftwarePlatform/rccl), since it has been synced up with NCCL 2.18, and RCCL already supports NPKit out-of-box.

**Comment by yzygitzh** [comment]
Hi @tks2004 you can also check https://github.com/Azure/msccl for NPKit support for NCCL 2.18.
Please checkout to latest main when you pull https://github.com/Azure/msccl-executor-nccl. We just enabled NPKit support for it.
